# Tutorial de TensorFlow. 
# Parte 1: Variables y constantes
TensorFlow (TF) es una librería opensource desarrollada por Google Brain para elaborar modelos de aprendizaje automático de forma rápida y simple. Es una de las librerías de este tipo más utilizadas junto a **h2o** y **pytorch** (de Facebook).

En términos simples, un tensor es una generalización de matrices y vectores a más dimensiones que las que suelen utilizarse, lo que posibilita el entrenamiento de modelos con mucha data de manera bastante ordenada.
Existen dos elementos fundamentales, las constantes y las variables, y ambas son categorías de los tensores.
La diferencia es que las constantes no se entrenan y pueden tener cualquier dimensión. Además, TF tiene varias funciones muy útiles para generar constantes de forma simple.
Las variables tiene tipo y forma fijas, pero puede cambiar su valor en la computación, lo cual es muy útil para la fase de entrenamiento al modelar. 

Una vez instalado anaconda, es posible instalar tensorflow con el instalador de python *pip*

In [1]:
# !pip install tensorflow
import tensorflow as tf

In [2]:
# 0D Tensor 
d0 = tf.ones((1,)) 

# 1D Tensor 
d1 = tf.ones((2,))

# 2D Tensor 
d2 = tf.ones((2, 2))

# 3D Tensor 
d3 = tf.ones((2, 2, 2))

# Print the 3D tensor 
print(d3.numpy())

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [7]:
# Para variables
# A1, unidimensional
A1 = tf.Variable([1, 2, 3, 4])

# Print
print(A1)

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4])>


In [8]:
# Es posible convertirlos a numpy, en que se imprime sus características y su valor
# Convert A1 to a numpy array and assign it to B1
B1 = A1.numpy()

# Print B1
print(B1)

[1 2 3 4]


## Operaciones básicas con TF
Para facilitar la creacion de matrices de constantes de ceros y unos de forma rápida, existen varios comandos

In [10]:
# Lo que va en los inputs va a depender, 
print(tf.constant([1, 2, 3]))

# De zeros y unos, el input son las dimensiones
print(tf.zeros([2, 2]))
print(tf.ones([2, 2]))

# Es posible hacer repeticiones, en este caso matriz de 3x3
print(tf.fill([3, 3], 7))

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[7 7 7]
 [7 7 7]
 [7 7 7]], shape=(3, 3), dtype=int32)


In [12]:
# Posible además tomar la dimensión de otro tensor, para crear uno nuevo con *_like
input_tensor = tf.zeros([2, 2])
print(tf.ones_like(input_tensor))

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


### Multiplicacion
El primer tipo es elemento a elemento (element-wise), la cual se puede realizar al tener dos tensores con dimensión idéntica. Se usa con `tf.multiply`.

El segundo es la multiplicación clásica con la que se sufre en Mate 2. Esta es la más importante, ya que es la que se utiliza para obtener coeficientes de regresión lineal mediante `tf.matmult`

$$Y = X \beta + \epsilon$$



In [15]:
# Se definen un par de tensores constantes
A1 = tf.constant([1, 2, 3, 4])
A23 = tf.constant([[1, 2, 3], [1, 6, 4]])

# Se definen B1 y B23 que tienen las mismas dimensiones
B1 = tf.ones_like(A1)
B23 = tf.ones_like(A23)

# Se hace multiplicación elemento a elemento
C1 = tf.multiply(A1, B1)
C23 = tf.multiply(A23, B23)

# Se imprimen los tensores
print('C1: {}'.format(C1.numpy()))
print('C23: {}'.format(C23.numpy()))

C1: [1 2 3 4]
C23: [[1 2 3]
 [1 6 4]]


In [19]:
# Por ejemplo, teniendo carecteristicas, parametros y precio
caracteristicas = tf.constant([[2, 24], [2, 26], [2, 57], [1, 37]])
params = tf.constant([[1000], [150]])
precio = tf.constant([[3913], [2682], [8617], [64400]])

# Se toman las predicciones
precio_pred = tf.matmul(caracteristicas, params)

# Se calcula el error
error = precio - precio_pred
print(error)


tf.Tensor(
[[-1687]
 [-3218]
 [-1933]
 [57850]], shape=(4, 1), dtype=int32)


### Suma
Al igual que en la multiplicación, tiene dos opciones, la primera es suma de tensores (`tf.add`), elemento a elemento, y suma de elementos dentro del mismo tensor (`tf.reduce_sum`).

In [22]:
# Utilizando el tensor características
caracteristicas = tf.constant([[2, 24], [2, 26], [2, 57], [1, 37]])

# reduce_sum toma un segundo argumento, en que señala si la suma se hace por filas (0), o columnas (1), y más segun las dimensiones del vector
print(tf.reduce_sum(caracteristicas, 1).numpy())
print(tf.reduce_sum(caracteristicas, 0).numpy())

[26 28 59 38]
[  7 144]


In [34]:
# La suma de matrices normal es simplemente
A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[5, 6], [7, 8]])
C = tf.add(A, B)
print(A)
print(B)
print(C)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


### Operaciones avanzadas

+ `tf.gradient`: calcula la pendiente de una función en algún punto.

+ `tf.reshape`: para cambiar la dimensión del tensor. Muy útil para el uso en tratamiento de imagenes, donde elementos de hasta 3 dimensiones que representan una imagen (alto, largo y color) deben convertirse en elementos de 1 para meterlos a la red neuronal.

+ `tf.random`: sirve para poblar un tensor con elementos aleatorios dados por alguna distribución.

En el siguiente ejemplo se creara un tensor con tonos de grises (2D) o colores (3D), y se pasará a un tensor de una sola. En futuros ejercicios se utilizará esto en ejercicios reales.

In [36]:
# Se genera una 'imagen' en escala de grises
gris = tf.random.uniform([2, 2], maxval=255, dtype='int32')

# Se cambia la dimensión del tensor. Para ello se debe tener claridad en que la nueva dimensión debe tener el mismo número de elementos que el original
gris_new = tf.reshape(gris, [2*2, 1])

# Se revisa
print(gris)
print(gris_new)

# Generate color image
color = tf.random.uniform([2, 2, 3], maxval=255, dtype='int32')
# Reshape color image
color = tf.reshape(color, [2*2, 3])

tf.Tensor(
[[205  59]
 [115 103]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[205]
 [ 59]
 [115]
 [103]], shape=(4, 1), dtype=int32)


El siguiente ejemplo es más avanzado, se utiliza la función `tf.gradient` para calcular máximo o mínimo de una función, en este caso $f(x) = x^2$. Queda como tarea al alumno repasar lo que hace la función `with` 

In [39]:
def calcular_gradiente(x0):
  	# Definir x como variable con valor inicial de x0
	x = tf.Variable(x0)
	with tf.GradientTape() as tape:
		tape.watch(x)
        # Definir y = x^2
		y = tf.multiply(x, x)
    # Return the gradient of y with respect to x
	return tape.gradient(y, x).numpy()

# Calcular y mostar gradientes en x = -1, 1, y 0
print(calcular_gradiente(-1.0))
print(calcular_gradiente(1.0))
print(calcular_gradiente(0.0))

-2.0
2.0
0.0
